CoderDojo/cp-dojos-service

data/dojos_config.js

https://github.com/CoderDojo/community-platform/issues/636

Update Dojo stage values

---

dojos.js

ref https://github.com/CoderDojo/community-platform/issues/672

updated dojo slug when one of slugs components changes.

---

dojos.js

ref https://github.com/CoderDojo/community-platform/issues/679

updated cmd_search_bounding_box to search by dojo name if search is provided

---

dojos.js
package.json
test/dojos-spec.js

Ckiss fixes

---

data/setup_dojo_steps.js

https://github.com/CoderDojo/community-platform/issues/708

fix tooltip text

---

dojos.js
test/dojos-spec.js

A first try to close CoderDojo/community-platform#728
What do you think?

Only set verifiedAt once

---

dojos.js

ref https://github.com/CoderDojo/community-platform/issues/802

verify child is part of dojo before trying to remove it as part of removing the parent

---

dojos.js

ref https://github.com/CoderDojo/community-platform/issues/809

fixed missing verifiedAt

---

email-templates/accept-badge-award-en_US/dojos-accept-badge-award.html.ejs
email-templates/accept-badge-award-en_US/dojos-accept-badge-award.text.ejs
email-templates/accept-badge-award-for-ninja-u13-en_US/html.ejs
email-templates/accept-badge-award-for-ninja-u13-en_US/text.ejs
email-templates/google-email-pass-en_US/dojos-google-email-pass.html.ejs
email-templates/google-email-pass-en_US/dojos-google-email-pass.text.ejs
email-templates/invite-user-en_US/dojos-invite-user.html.ejs
email-templates/invite-user-en_US/dojos-invite-user.text.ejs
email-templates/invited-to-session-en_US/html.ejs
email-templates/session-cancelled-en_US/html.ejs
email-templates/ticket-application-approved-en_US/html.ejs
email-templates/ticket-application-received-en_US/html.ejs
email-templates/user-left-dojo-en_US/dojos-user-left-dojo.html.ejs
email-templates/user-left-dojo-en_US/dojos-user-left-dojo.text.ejs
email-templates/user-request-to-join-en_US/dojos-user-request-to-join.html.ejs
email-templates/user-request-to-join-en_US/dojos-user-request-to-join.text.ejs

https://github.com/CoderDojo/community-platform/issues/614

Update email template

---

dojos.js

Will resolve https://github.com/CoderDojo/community-platform/issues/867

No need to check email address as well as token for invite acceptance

---

package.json

License: Change BSD to MIT

---

scripts/database/pg/migrations/013.do.add-tao-verified.sql

PR for https://github.com/CoderDojo/community-platform/issues/741

Adding tao verification pgsql migration

---

scripts/database/pg/migrations/014.do.add-attendee-column.sql

Ref: https://github.com/CoderDojo/community-platform/issues/736
If someone could try run this migration that would be great. My dojo service migrations don't seem to run on startup. I have tested the migration in a different service though and it worked.

i736: Migration for attendee column

---

config/config.js

path.resolve doesnt really suit an upstart job..
cf https://github.com/CoderDojo/community-platform/issues/772

Put Google vars as pure env to suit prod conf

---

dojos.js
email-templates/new-dojo-en_US/html.ejs
email-templates/new-dojo-en_US/text.ejs

Add email notification on dojo-creation

---

dojos.js
test/dojos-spec.js

A small fix for issue CoderDojo/community-platform#904 with a simple test case.
Just getting acquainted with the code, so just let me know if I'm missing anything.

Case insensitive sort for dojos on list. Fixes CoderDojo/community-platform#904

---

dojos.js
lib/add-children-parent-dojo.js

so that founders have the right to have a social life and children, too :o)

Add child when dojo is created

---

dojos.js
email-templates/new-dojo-en_US/html.ejs

Fix https://github.com/CoderDojo/community-platform/issues/955

Change reception email to allow copy-paste && reply-to the dojo email

---

dojos.js

Fix https://github.com/CoderDojo/community-platform/issues/704

Change email responseTo for invit

---

dojos.js

But doesn't if it's another, which means you need to have them identical for both replyTo & from
Also, explamation point, because, it's a new dojo !!

Zendesk ignore replyTo if it's an internal email

---

email-templates/ticket-application-cancelled-en_US/html.ejs
email-templates/ticket-application-cancelled-en_US/text.ejs

Fix CoderDojo/community-platform#944

Add ticket cancellation template

---

dojos.js
lib/export-csv.js
package.json

close [/community-platform#810](https://github.com/CoderDojo/community-platform/issues/810)

add export dojo users command

---

config/config.js
dojos.js
service.js
test/dojos-spec.js

Yahoo doens't accept that we spoof the From address

Fix certain email not working through sendgrid

---

dojos.js

callback params order must have changed i guess

Fix remove user due to seneca upgrade

---

lib/add-children-parent-dojo.js

Calling multiple time the wrong callback, thanks new data test workflow, it helps finding bugs :)

Fix callback to join kids to their parent's dojo

---

dojos.js

limit the amount of admins details returned when api queried

limit of admin data returned

---

circle.yml

for [#988](https://github.com/CoderDojo/community-platform/issues/988)

add maltese slovenian slovak ukrainian french and Argentinian

---

dojos.js

Restrict saved properties

---

dojos.js
lib/export-csv.js

https://github.com/CoderDojo/community-platform/issues/1095

Added parent email csv export

---

lib/export-csv.js

Should finish https://github.com/CoderDojo/community-platform/issues/1095

Add attendances to exportCSV

---

config/permissions-rules.js
dojos.js
lib/dojos/accept-join-request.js
lib/dojos/decline-join-request.js
lib/dojos/search-join-requests.js
test/fixtures/e2e/dojo-members.json

Required for https://github.com/CoderDojo/cp-zen-platform/pull/1104

Add support for search of join requests

---

email-templates/polls-sms-notification-en_US/html.ejs
email-templates/polls-sms-notification-en_US/text.ejs
lib/poll/channels/queue-email-poll.js
lib/poll/channels/queue-sms-poll.js
lib/poll/channels/save-sms-result.js
lib/poll/get-poll-setup.js
test/fixtures/e2e/polls.json
test/lib/insert-test-dojos.js

When eror is business related, return a 400 to Twilio
add error handler
remove console log

Make error handling in poll non-fatal

---

dojos.js

[#1031](https://github.com/CoderDojo/community-platform/issues/1031)

The replyTo email of invite request emails from mentors is now the email of the mentor

---

lib/export-csv.js

Expand Manage Users CSV export #1173
Added Age and Parent Names, also cleaned up Type column, which was returning JSON formatted data in cell.
Thanks,
James

Added Age and Parent Name to the CSV Export

---

dojos.js

Added event object to content. This is untested locally since smtp doesn't work on my local environment.

Added Specific Event to Email Notifications

---

.dockerignore
dev.Dockerfile
docker-entrypoint.sh

dockerfile for development env to be used with a volume

add dev dockerfile

---

circle.yml

When on staging branch, use cp-translations translations

Take cp-translations from staging

---

lib/controllers/dojo/submit.js
lib/controllers/dojo/submit.spec.js
lib/controllers/lead/save.js
lib/controllers/lead/save.spec.js

user rather than the latest one to save it

SAD : Force every user values to be the original lead user

---

lib/migrate-old-lead.js

We reuse the same act : it still serve the same goal and should still be ran once.

 #150128310 Remove extra fields from old-leads

---

lib/controllers/dojo/submit.js
lib/controllers/lead/submit.js

#150335369 Capitalize dojo email title to allow them to be sent

---

lib/controllers/dojo/delete.spec.js
lib/controllers/dojo/save.spec.js
lib/controllers/dojo/submit.js
lib/controllers/dojo/submit.spec.js
lib/controllers/dojo/verify.spec.js
lib/controllers/lead/submit.js
lib/controllers/lead/submit.spec.js
test/lib/mock.js

Add extra tests regarding CDF handling

Remove email notification when the lead is submitted by a CDF

---

lib/controllers/lead/delete.js
lib/migrate-old-lead.js
scripts/database/pg/migrations/024.do.update-v-dojoleads-deleted.sql

Need to run post deployment : 
``` curl -d '{"role":"cd-dojos", "cmd":"migrate-v1-leads"}' -H 'Content-Type: application/json' -H 'Accept: application/json, text/plain, */*' -H 'Cache-Control: no-cache' http://localhost:10301/act ```

149269373 Allow CDF to search through leads

---

lib/controllers/lead/save.js

Story : https://www.pivotaltracker.com/story/show/151839836

#151839836 remove champion lead address from transferred field to profile

---

lib/controllers/dojo/save.js
lib/controllers/dojo/save.spec.js
package.json

Add a new step to dojo save controller
fix package.json absent s/bash/sh/g for docker
Pray for us to have pub/sub one day to replace those inter-dependencies btwn dojo/event

#152002813-Change-address-events-dojo-change

---

lib/dojos/users/notify.js

And it was working, because it wasn't filtering.

Fix faulty query which wasn't filtering anything

---

config/permissions-rules.js

Remove faulty perm for search leads

---

config/permissions-rules.js

disallow sending custom emails for anybody but a dojo-admin

Ensure you request to join only yourself

---

config/permissions-rules.js

it's not a controller, while it should, but eh..

Move the act permission down to its definition

---

lib/perm/have-permissions-on-user.js
lib/save-usersdojo.js

Replace have_perm_on_user by have_perm_on_dojo

---

dojos.js

in this scenario, this POST should be a DELETE and its params for is-self is coming from the url

Ensure a single source of truth for data

---

package.json
yarn.lock

Honestly, this is a wild hope more than anything else

Change version of i18n without global store

---

lib/dojos/users/notifyAll.js

Ensure we don't notify deleted users

---

dojos.js
lib/backfill-dojo-county-state.js
package.json
yarn.lock

Backfilling of Dojos locations

---

lib/controllers/lead/save.js
scripts/database/pg/migrations/029.do.add-safeguarding-sponsor.sql
scripts/database/pg/migrations/030.do.remove-unused-dojolead-column.sql

- Also copy across from Lead->Dojo when saving.

Add safeguarding sponsor fields to Dojos table.

---

lib/controllers/lead/save.js

443: Make checking of variable more robust
